- name: Check if Terraform binary exists
  stat:
    path: /usr/bin/terraform
  register: terraform_binary
  tags:
    - terraform

- name: Download HashiCorp GPG key
  shell: "curl https://apt.releases.hashicorp.com/gpg | gpg --dearmor > /tmp/hashicorp.gpg"
  tags:
    - terraform
  when: not terraform_binary.stat.exists

- name: Install HashiCorp GPG key
  copy:
    src: "/tmp/hashicorp.gpg"
    dest: "/etc/apt/trusted.gpg.d/hashicorp.gpg"
    owner: root
    group: root
    mode: '0644'
  tags:
    - terraform
  when: not terraform_binary.stat.exists

- name: Add HashiCorp repository
  apt_repository:
    repo: "deb https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes
  tags:
    - terraform
  when: not terraform_binary.stat.exists

- name: Install Terraform
  apt:
    name: terraform
    state: present
    update_cache: yes
  tags:
    - terraform
  when: not terraform_binary.stat.exists
